In [39]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [10]:
listed = pd.read_csv("listed_final.csv", low_memory=False)
sold = pd.read_csv("sold_final.csv", low_memory=False)

In [3]:
listed.shape, sold.shape

((540318, 61), (397017, 68))

In [7]:
int(((sold["Longitude"] > 0) | (sold["Latitude"] < 0)).sum())

31

In [9]:
(sold["Longitude"] > 0) | (sold["Latitude"] < 0)

0         False
1         False
2         False
3         False
4         False
          ...
397012    False
397013    False
397014    False
397015    False
397016    False
Length: 397017, dtype: bool

In [11]:
date_cols = ["CloseDate", "PurchaseContractDate", "ListingContractDate", "ContractStatusChangeDate"]
for df in [listed, sold]:
    for col in date_cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

In [6]:
sold[date_cols].info()

<class 'pandas.DataFrame'>
RangeIndex: 396721 entries, 0 to 396720
Data columns (total 4 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CloseDate                 396721 non-null  datetime64[us]
 1   PurchaseContractDate      396527 non-null  datetime64[us]
 2   ListingContractDate       396720 non-null  datetime64[us]
 3   ContractStatusChangeDate  396132 non-null  datetime64[us]
dtypes: datetime64[us](4)
memory usage: 12.1 MB

In [12]:
main_fields = ["ListingKey", "ListingContractDate", "ListPrice", "ClosePrice",
               "PurchaseContractDate", "CloseDate", "LivingArea", "BedroomsTotal",
               "BathroomsTotalInteger", "Latitude", "Longitude", "UnparsedAddress"]

In [13]:
listed.info()

<class 'pandas.DataFrame'>
RangeIndex: 540318 entries, 0 to 540317
Data columns (total 61 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   OriginalListPrice            539549 non-null  float64
 1   ListingKey                   540318 non-null  int64
 2   ListAgentEmail               493109 non-null  str
 3   CloseDate                    163479 non-null  datetime64[us]
 4   ClosePrice                   143182 non-null  float64
 5   ListAgentFirstName           536077 non-null  str
 6   ListAgentLastName            540279 non-null  str
 7   Latitude                     460161 non-null  float64
 8   Longitude                    460161 non-null  float64
 9   UnparsedAddress              539634 non-null  str
 10  PropertyType                 540318 non-null  str
 11  LivingArea                   539766 non-null  float64
 12  ListPrice                    540318 non-null  float64
 13  DaysOnMarket                 540318 non-null  int64
 14  ListOfficeName               540318 non-null  str
 15  BuyerOfficeName              154582 non-null  str
 16  CoListOfficeName             121010 non-null  str
 17  ListAgentFullName            540228 non-null  str
 18  CoListAgentFirstName         120525 non-null  str
 19  CoListAgentLastName          120925 non-null  str
 20  BuyerAgentMlsId              156687 non-null  str
 21  BuyerAgentFirstName          156072 non-null  str
 22  BuyerAgentLastName           156795 non-null  str
 23  AssociationFeeFrequency      230872 non-null  str
 24  MLSAreaMajor                 467199 non-null  str
 25  CountyOrParish               540318 non-null  str
 26  MlsStatus                    540318 non-null  str
 27  ElementarySchool             64349 non-null   str
 28  AttachedGarageYN             445868 non-null  object
 29  ParkingTotal                 540298 non-null  float64
 30  PropertySubType              539067 non-null  str
 31  LotSizeAcres                 495771 non-null  float64
 32  SubdivisionName              198972 non-null  str
 33  BuyerOfficeAOR               144572 non-null  str
 34  YearBuilt                    539385 non-null  float64
 35  BuyerAgencyCompensationType  79005 non-null   str
 36  StreetNumberNumeric          539455 non-null  float64
 37  ListingId                    540318 non-null  str
 38  BathroomsTotalInteger        540263 non-null  float64
 39  City                         539744 non-null  str
 40  BuyerAgencyCompensation      78985 non-null   float64
 41  BedroomsTotal                540171 non-null  float64
 42  ContractStatusChangeDate     534265 non-null  datetime64[us]
 43  PurchaseContractDate         264303 non-null  datetime64[us]
 44  ListingContractDate          540318 non-null  datetime64[us]
 45  StateOrProvince              540265 non-null  str
 46  MiddleOrJuniorSchool         64476 non-null   str
 47  FireplaceYN                  539746 non-null  object
 48  Stories                      445808 non-null  float64
 49  HighSchool                   84446 non-null   str
 50  Levels                       481986 non-null  str
 51  LotSizeArea                  496610 non-null  float64
 52  MainLevelBedrooms            293741 non-null  float64
 53  NewConstructionYN            503240 non-null  object
 54  GarageSpaces                 510278 non-null  float64
 55  HighSchoolDistrict           377717 non-null  str
 56  PostalCode                   540305 non-null  str
 57  AssociationFee               410343 non-null  float64
 58  LotSizeSquareFeet            496435 non-null  float64
 59  year_month                   540318 non-null  str
 60  rate_30yr_fixed              540318 non-null  float64
dtypes: datetime64[us](4), float64(20), int64(2), object(3), str(32)
memory usage: 251.5+ MB

In [11]:
all(listed["ListingKey"] == listed["ListingKeyNumeric"])

True

In [42]:
sorted(sold.columns)

['AssociationFee',
 'AssociationFeeFrequency',
 'AttachedGarageYN',
 'BathroomsTotalInteger',
 'BedroomsTotal',
 'BuyerAgencyCompensation',
 'BuyerAgencyCompensationType',
 'BuyerAgentAOR',
 'BuyerAgentFirstName',
 'BuyerAgentLastName',
 'BuyerAgentMlsId',
 'BuyerOfficeAOR',
 'BuyerOfficeName',
 'City',
 'CloseDate',
 'ClosePrice',
 'CoListAgentFirstName',
 'CoListAgentLastName',
 'CoListOfficeName',
 'ContractStatusChangeDate',
 'CountyOrParish',
 'DaysOnMarket',
 'ElementarySchool',
 'FireplaceYN',
 'Flooring',
 'GarageSpaces',
 'HighSchool',
 'HighSchoolDistrict',
 'Latitude',
 'Levels',
 'ListAgentAOR',
 'ListAgentEmail',
 'ListAgentFirstName',
 'ListAgentFullName',
 'ListAgentLastName',
 'ListOfficeName',
 'ListPrice',
 'ListingContractDate',
 'ListingId',
 'ListingKey',
 'ListingKeyNumeric',
 'LivingArea',
 'Longitude',
 'LotSizeAcres',
 'LotSizeArea',
 'LotSizeSquareFeet',
 'MLSAreaMajor',
 'MainLevelBedrooms',
 'MiddleOrJuniorSchool',
 'MlsStatus',
 'NewConstructionYN',
 'OriginalListPrice',
 'ParkingTotal',
 'PoolPrivateYN',
 'PostalCode',
 'PropertySubType',
 'PropertyType',
 'PurchaseContractDate',
 'StateOrProvince',
 'Stories',
 'StreetNumberNumeric',
 'SubdivisionName',
 'UnparsedAddress',
 'ViewYN',
 'YearBuilt',
 'latfilled',
 'lonfilled',
 'rate_30yr_fixed',
 'year_month']

In [27]:
neg_days_addr = sold[sold["DaysOnMarket"] < 0]["UnparsedAddress"]

sold[sold["UnparsedAddress"].isin(neg_days_addr)].shape

(52, 69)

In [28]:
neg_days_addr.shape

(46,)

In [31]:
sold[(sold["UnparsedAddress"].isin(neg_days_addr)) & (sold["DaysOnMarket"] >= 0)]["UnparsedAddress"]

41879               45355 Miami Circle
86100     1025 N Tippecanoe Avenue 122
115149                 728 Malat Drive
155321          2230 N Eastwood Avenue
160684     28661 Crystal Heights Court
268544            8214 Platinum Street
Name: UnparsedAddress, dtype: str

In [36]:
sold[sold["UnparsedAddress"] == "1025 N Tippecanoe Avenue 122"][main_fields + ["DaysOnMarket"]]

,ListingKey,ListingContractDate,ListPrice,ClosePrice,PurchaseContractDate,CloseDate,LivingArea,BedroomsTotal,BathroomsTotalInteger,Latitude,Longitude,UnparsedAddress,DaysOnMarket
37001,1052236827,2023-12-08,135000.0,135000.0,2024-02-12,2024-03-08,708.0,1.0,1.0,34.118923,-117.260126,1025 N Tippecanoe Avenue 122,-19
86100,1069712675,2024-04-19,209900.0,210000.0,2024-05-03,2024-06-07,708.0,1.0,1.0,34.119162,-117.259896,1025 N Tippecanoe Avenue 122,9

In [16]:
sold[sold["DaysOnMarket"] < 0][main_fields + ["DaysOnMarket"]]

,ListingKey,ListingContractDate,ListPrice,ClosePrice,PurchaseContractDate,CloseDate,LivingArea,BedroomsTotal,BathroomsTotalInteger,Latitude,Longitude,UnparsedAddress,DaysOnMarket
6,1063453216,2023-11-17,1950000.0,1950000.0,2023-12-19,2024-01-22,2100.0,3.0,0.0,39.419080,-123.814842,31451 Bay View Avenue,-36
11214,1062122119,2024-02-24,899000.0,899000.0,2024-02-24,2024-02-26,2533.0,2.0,3.0,33.718784,-116.320070,45410 Delgado Drive,-13
11381,1061302766,2024-02-16,372000.0,372000.0,2024-02-16,2024-02-23,1488.0,3.0,2.0,33.978398,-117.364937,2956 Mission Inn Avenue,-10
18698,1052574395,2023-12-12,699900.0,700000.0,2023-12-23,2024-02-05,1382.0,4.0,2.0,34.224970,-119.192996,1350 Gardenia Street,-10
23005,1045653374,2023-09-25,485410.0,476985.0,2024-01-29,2024-02-29,1342.0,3.0,2.0,33.947311,-117.033062,11508 Hinton Court,-13
24397,1063549350,2024-01-30,799000.0,799000.0,2024-02-02,2024-03-21,1284.0,3.0,2.0,34.425577,-119.291855,11905 Silver Spur Street,-48
24405,1063528331,2024-01-11,899000.0,810000.0,2024-01-22,2024-03-19,1164.0,2.0,1.0,39.383806,-123.789254,31530 Emerald Drive,-58
24441,1063458939,2024-03-03,880000.0,880000.0,2024-03-04,2024-03-15,2018.0,3.0,3.0,34.274754,-119.183685,8214 Platinum Street,-14
29425,1060256290,2024-02-07,865000.0,875000.0,2024-02-10,2024-03-08,1987.0,2.0,2.0,34.225207,-118.981438,31303 Village 31,-2
30176,1060153479,2024-01-31,1599000.0,1625000.0,2024-02-06,2024-03-21,2130.0,4.0,3.0,34.244449,-118.265167,3929 El Moreno Street,-1
30268,1060140950,2024-02-04,750000.0,780000.0,2024-03-04,2024-03-22,1490.0,3.0,2.0,33.959415,-118.082646,9135 Millergrove Drive,-6
35258,1055059543,2024-01-09,599888.0,615000.0,2024-02-27,2024-03-18,920.0,2.0,2.0,32.910210,-117.159392,10644 Dabney Drive 150,-3
35572,1054201667,2024-01-03,399900.0,390000.0,2024-01-08,2024-03-04,722.0,1.0,1.0,34.173167,-118.843329,2486 Pleasant Way C,-2
35925,1054117211,2024-01-04,500000.0,505000.0,2024-02-10,2024-03-13,1442.0,3.0,2.0,34.091510,-117.340055,2305 Huff Street,-5
36249,1054015025,2023-12-26,1650000.0,1500000.0,2023-12-30,2024-03-01,2538.0,3.0,3.0,34.422994,-119.305875,2046 Los Encinos Road,-6
36506,1053227106,2023-12-21,725000.0,715000.0,2024-02-05,2024-03-01,2284.0,4.0,2.0,33.527214,-117.107251,41019 Simi Court,-10
37054,1052236827,2023-12-08,135000.0,135000.0,2024-02-12,2024-03-08,708.0,1.0,1.0,34.118923,-117.260126,1025 N Tippecanoe Avenue 122,-19
37873,1047718452,2023-11-15,1250000.0,1120000.0,2024-03-21,2024-03-22,3108.0,3.0,3.0,33.719019,-116.337664,45355 Miami Circle,-57
50344,1061567895,2024-02-14,799999.0,825000.0,2024-03-28,2024-04-17,1618.0,4.0,2.0,33.765785,-117.855651,2230 N Eastwood Avenue,-2
67612,1064982371,2024-03-27,759880.0,765000.0,2024-04-23,2024-05-20,1308.0,3.0,2.0,34.188599,-118.947732,728 Malat Drive,-2
74057,1058398892,2024-01-19,839000.0,840000.0,2024-04-12,2024-05-21,1150.0,3.0,2.0,33.978121,-117.897218,18665 Bellorita Street,-43
85688,1071120350,2024-04-22,675000.0,725000.0,2024-05-31,2024-06-25,1519.0,3.0,2.0,33.934891,-118.189534,4701 Abbott Road,-18
89212,1064877546,2024-03-26,899000.0,877000.0,2024-06-03,2024-06-18,1672.0,4.0,2.0,33.794960,-116.958689,22530 San Jacinto Avenue,-84
90266,1062143995,2024-03-08,459900.0,470000.0,2024-04-29,2024-06-27,1283.0,4.0,2.0,33.905117,-117.234649,14849 Silvertree Road,-1
141443,1035190518,2023-03-29,720000.0,745000.0,2024-06-11,2024-09-03,1143.0,3.0,2.0,33.754077,-117.924370,1022 West Street,-56
151404,1079408688,2024-08-12,920888.0,940000.0,2024-09-23,2024-10-09,1423.0,3.0,2.0,33.722897,-117.893170,1826 W Saint Andrew Place,-8
175501,1093571353,2024-08-25,600000.0,805000.0,2024-11-18,2024-12-03,1063.0,3.0,1.0,33.742840,-117.974902,8841 Elvira Avenue,-6
209112,1037231656,2023-05-04,83000.0,105000.0,2024-04-26,2025-02-18,1368.0,2.0,2.0,33.732492,-116.988397,1670 Vista Grande Drive,-288
221405,1093723828,2024-10-10,365750.0,365750.0,2025-02-14,2025-03-07,2147.0,3.0,3.0,33.744798,-116.376986,18 Camisa Lane,-5
232139,1107421269,2025-02-19,799000.0,825000.0,2025-03-26,2025-04-21,2358.0,4.0,4.0,34.084546,-117.604177,2214 E La Deney Way,-12
232367,1107324934,2025-02-19,939900.0,950000.0,2025-03-07,2025-04-18,1381.0,3.0,2.0,34.266276,-118.499387,10746 Forbes Avenue,-3
234248,1104327481,2025-02-04,568000.0,555000.0,2025-03-14,2025-04-11,814.0,2.0,2.0,33.788997,-117.792632,5722 E Stillwater Avenue 57,-4
253988,1095580381,2024-11-21,895000.0,900000.0,2025-03-22,2025-05-15,1620.0,4.0,2.0,34.145873,-117.917559,762 W Virginia Ann Drive,-34
260061,1112514824,2025-05-01,489000.0,500000.0,2025-06-13,2025-06-23,1547.0,3.0,2.0,34.667087,-118.213155,4628 W Avenue K8,-26
267631,1108279128,2025-03-04,1075000.0,1090000.0,2025-04-27,2025-06-17,3660.0,5.0,3.0,34.431424,-118.438599,28661 Crystal Heights Court,-7
279990,1112882699,2025-05-07,599000.0,653000.0,2025-07-01,2025-07-03,1036.0,3.0,2.0,33.925834,-118.282024,443 W 118th Place,-9
284796,1107324362,2025-02-12,150000.0,130000.0,2025-07-15,2025-07-24,1228.0,4.0,2.0,35.129300,-117.977282,8436 Walpole Avenue,-63
297819,1112971484,2025-05-08,239000.0,238000.0,2025-08-03,2025-08-29,1260.0,3.0,2.0,37.296684,-120.417309,599 N Easy Street,-14
319107,1133974483,2025-08-13,549999.0,565000.0,2025-09-26,2025-10-23,2250.0,3.0,3.0,34.568773,-118.009087,37762 67th Street E,-7
321257,1131827231,2025-09-03,750000.0,605000.0,2025-09-29,2025-10-29,802.0,2.0,1.0,34.067885,-118.174026,5013 O Sullivan Drive,-2
327231,1119659079,2025-07-18,859999.0,860000.0,2025-10-21,2025-10-27,1124.0,2.0,1.0,33.747213,-118.303789,1242 W Summerland Avenue,-4
331548,1109524000,2025-03-31,654607.0,584990.0,2025-07-29,2025-10-10,2311.0,3.0,3.0,33.733205,-117.221152,26655 Silver Ore Rd. Drive,-21
345166,1061933679,2024-02-08,675000.0,560000.0,2025-07-08,2025-11-06,1333.0,3.0,1.0,33.997916,-118.325001,4933 7th Avenue,-65
345171,1058168677,2024-01-12,600000.0,615000.0,2025-07-07,2025-11-06,1189.0,3.0,2.0,34.068284,-117.624698,502 N Glenn Place,-265
359060,1095526549,2024-11-20,455000.0,455000.0,2025-12-01,2025-12-03,2189.0,3.0,2.0,34.504106,-117.290582,17101 Baywood Way,-4
378087,1145466193,2025-11-02,429900.0,445000.0,2026-01-04,2026-02-09,1774.0,3.0,2.0,33.722802,-117.009023,1457 Angelus Hill,-14
411695,1146833920,2025-11-21,530000.0,530000.0,2026-02-15,2026-04-28,2143.0,5.0,2.0,34.161144,-117.256022,1425 39th E,-39

In [17]:
sold[sold["ClosePrice"] < 100000][main_fields]

,ListingKey,ListingContractDate,ListPrice,ClosePrice,PurchaseContractDate,CloseDate,LivingArea,BedroomsTotal,BathroomsTotalInteger,Latitude,Longitude,UnparsedAddress
276,1055489660,2024-01-12,72500.0,65000.0,2024-01-12,2024-01-16,1344.0,2.0,2.0,35.719551,-118.456103,1235 Sycamore Drive
961,1053881167,2023-12-12,49000.0,32000.0,2024-01-06,2024-01-22,624.0,2.0,2.0,33.613533,-114.572268,251 Ward Street
1136,1053107592,2023-12-05,84000.0,85000.0,2023-12-24,2024-01-30,1152.0,2.0,2.0,34.493531,-117.324593,13393 Mariposa Rd 125
1178,1053078026,2023-12-19,99900.0,85000.0,2024-01-08,2024-01-19,1440.0,3.0,2.0,40.022076,-122.090884,7775 Buddy Lane
1267,1052850874,2023-12-19,99000.0,99000.0,2024-01-03,2024-01-31,1008.0,4.0,1.0,39.933825,-121.731964,115 Black Apple Way
...,...,...,...,...,...,...,...,...,...,...,...,...
412709,1137067053,2025-09-27,65000.0,47500.0,2026-03-26,2026-04-16,192.0,1.0,0.0,34.174305,-116.292631,62823 Appian Way
412854,1133945925,2025-09-12,95000.0,80000.0,2026-03-23,2026-04-07,1440.0,3.0,2.0,38.909037,-122.613172,9532 Bell Avenue
412904,1132746799,2025-09-06,99900.0,93000.0,2026-03-09,2026-04-08,975.0,1.0,2.0,33.612929,-117.744200,24055 Paseo Del Lago 1255
413069,1127193243,2025-08-15,55000.0,55000.0,2026-03-12,2026-04-08,900.0,3.0,1.0,35.589952,-118.490296,7 Pioneer Place
413488,1108955179,2025-03-18,74900.0,75000.0,2026-04-02,2026-04-17,1360.0,3.0,2.0,35.790937,-117.361034,84646 12th Street

In [24]:
sold[(sold["ClosePrice"] / sold["OriginalListPrice"]) < 0.1][["OriginalListPrice", "ClosePrice"]]

        OriginalListPrice  ClosePrice
7651             349500.0     31500.0
9087            6080009.0    565000.0
9916           19050000.0   1750000.0
10444           2250000.0    180000.0
14158         775900000.0    775900.0
...                   ...         ...
407595         18800000.0   1660000.0
408550         10595000.0   1050000.0
409204         33390000.0    325000.0
411476          6660000.0    640000.0
413148          9500000.0    860000.0

[255 rows x 2 columns]

In [28]:
sorted(sold["ClosePrice"] / sold["OriginalListPrice"], reverse=True)

[nan,
 nan,
 972222.2222222221,
 958333.3333333334,
 600000.0,
 100000.0,
 95000.0,
 11188.40579710145,
 9953.409572215163,
 9825.174825174825,
 9782.608695652174,
 1128.0,
 1072.1442885771544,
 1036.4464692482916,
 1033.3575054387238,
 1027.5689223057643,
 1001.4306151645208,
 1001.1918951132301,
 1000.0,
 1000.0,
 1000.0,
 992.1875,
 990.0990099009902,
 985.5072463768116,
 979.8019596039192,
 971.5639810426541,
 971.0681749924918,
 968.1978798586572,
 966.3157894736842,
 962.5,
 961.961961961962,
 960.0,
 958.9041095890411,
 957.4468085106383,
 956.0,
 944.5300462249614,
 937.5,
 926.7563527653214,
 912.7789046653144,
 911.4754098360655,
 908.0459770114943,
 901.8036072144289,
 899.2805755395683,
 890.9090909090909,
 872.9139922978177,
 858.3690987124463,
 785.7622565480189,
 783.1325301204819,
 764.1921397379913,
 695.0,
 680.9338521400779,
 179.64255558682802,
 172.77578514565656,
 111.48671022128556,
 99.07407407407408,
 98.03921568627452,
 97.47292418772564,
 75.19739315703723,
 58.064516129032256,
 17.581619014411903,
 13.333333333333334,
 12.703379224030037,
 11.839708561020036,
 11.541762848023733,
 11.310734463276836,
 10.953527272727273,
 10.717896865520729,
 10.634780692087283,
 10.6256641040065,
 10.59322033898305,
 10.560747663551401,
 10.4,
 10.267857142857142,
 10.248198558847077,
 10.236220472440944,
 10.234375,
 10.222297942947726,
 10.093457943925234,
 10.003847633705272,
 10.00057603686636,
 10.000142859183702,
 10.000005750802396,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 9.96,
 9.946983785686893,
 9.928571428571429,
 9.920634920634921,
 9.917355371900827,
 9.874213836477987,
 9.864864864864865,
 9.844271412680756,
 9.82905982905983,
 9.818181818181818,
 9.80952380952381,
 9.783152627189324,
 9.727361157828707,
 9.698492462311558,
 9.64974982130093,
 9.621848739495798,
 9.586799399972726,
 9.58117123795404,
 9.562841530054644,
 9.5625,
 9.5,
 9.454545454545455,
 9.453837597330367,
 9.44206008583691,
 9.44,
 9.40665870873988,
 9.276437847866418,
 9.222222222222221,
 9.152542372881356,
 9.13613749434645,
 9.113636363636363,
 9.0,
 8.93127791024347,
 8.92994611239415,
 8.897243107769423,
 8.807045636509207,
 8.8,
 8.757297748123436,
 8.755102040816327,
 8.724832214765101,
 8.653846819526677,
 8.58974358974359,
 8.5,
 8.485714285714286,
 8.36,
 8.148148148148149,
 8.130434782608695,
 7.798165137614679,
 7.103182225637085,
 6.75,
 6.563706563706564,
 5.511022044088176,
 5.454545454545454,
 3.7142857142857144,
 3.67,
 3.3,
 2.8900000578000014,
 2.581453634085213,
 2.5,
 2.454873646209386,
 2.4128073184676957,
 2.2342064714946073,
 2.198364008179959,
 2.1026026026026026,
 2.0,
 1.9682539682539681,
 1.954354870912749,
 1.95,
 1.8998666666666666,
 1.8996415770609318,
 1.879357381024553,
 1.8268268268268268,
 1.8147684605757197,
 1.811623246492986,
 1.7950115955829276,
 1.7882352941176471,
 1.776061776061776,
 1.7724413950829045,
 1.7573221757322175,
 1.7529215358931554,
 1.7510791366906475,
 1.75,
 1.7384615384615385,
 1.7355371900826446,
 1.7353333333333334,
 1.7296482412060301,
 1.719056974459725,
 1.7085427135678393,
 1.699249829506706,
 1.696969696969697,
 1.696969696969697,
 1.693532834045836,
 1.6896120150187734,
 1.6889632107023411,
 1.6834170854271358,
 1.6764705882352942,
 1.6733333333333333,
 1.6666666666666667,
 1.6607773851590106,
 1.6602316602316602,
 1.6548881036513545,
 1.6332378223495703,
 1.6288384512683578,
 1.623246492985972,
 1.6181818181818182,
 1.6146993318485523,
 1.6129032258064515,
 1.5849056603773586,
 1.5833333333333333,
 1.5789473684210527,
 1.5770609318996416,
 1.5733385777952593,
 1.5728813559322035,
 1.5719063545150502,
 1.5681233933161953,
 1.5634218289085546,
 1.560846560846561,
 1.5606281407035176,
 1.55902004454343,
 1.5585858585858585,
 1.5577889447236182,
 1.5577619047619047,
 1.5538461538461539,
 1.5500038750096876,
 1.546162402669633,
 1.5454545454545454,
 1.536050156739812,
 1.5331664580725908,
 1.5312131919905771,
 1.5285714285714285,
 1.5277404444444445,
 1.5251708191317428,
 1.525,
 1.5239154616240267,
 1.5217391304347827,
 1.5217391304347827,
 1.5204678362573099,
 1.5172413793103448,
 1.5135135135135136,
 1.5083333333333333,
 1.506276150627615,
 1.5053763440860215,
 1.5015015015015014,
 1.5011119347664936,
 1.5011119347664936,
 1.5001680188181077,
 1.4941176470588236,
 1.487695749440716,
 1.4852941176470589,
 1.4764764764764764,
 1.4752370916754478,
 1.473551637279597,
 1.4728682170542635,
 1.471571906354515,
 1.4692307692307693,
 1.4666666666666666,
 1.4637904468412943,
 1.461187214611872,
 1.4548494983277591,
 1.4529058116232465,
 1.4509018036072143,
 1.45,
 1.45,
 1.45,
 1.4491525423728813,
 1.4488935721812435,
 1.4469914040114613,
 1.4460511679644048,
 1.4444765439231984,
 1.4440734557595993,
 1.4428857715430863,
 1.44,
 1.4392991239048811,
 1.4392991239048811,
 1.4388489208633093,
 1.438698915763136,
 1.4376341791900578,
 1.4358717434869739,
 1.4352469959946594,
 1.4336917562724014,
 1.4335839598997493,
 1.4330874604847208,
 1.4330874604847208,
 1.432,
 1.4292929292929293,
 1.4285714285714286,
 1.4285714285714286,
 1.425790224100118,
 1.424778761061947,
 1.4230769230769231,
 1.422550052687039,
 1.421136909527622,
 1.4209591474245116,
 1.4166666666666667,
 1.414715719063545,
 1.4144877839691385,
 1.4128256513026052,
 1.4108674928503337,
 1.4106844741235391,
 1.410491546540141,
 1.4099216710182767,
 1.4076923076923078,
 1.4071632270168855,
 1.4071294559099436,
 1.407035175879397,
 1.4062882809309922,
 1.4046822742474916,
 1.4046511627906977,
 1.4036979969183359,
 1.402805611222445,
 1.4026666666666667,
 1.4017521902377972,
 1.4014094094094094,
 1.4000014000014,
 1.3964151729887453,
 1.3947271142109852,
 1.3932868904369855,
 1.391465677179963,
 1.3909774436090225,
 1.3907815631262526,
 1.3904338153503892,
 1.38996138996139,
 1.3895216400911161,
 1.3884297520661157,
 1.385078947368421,
 1.3837837837837839,
 1.3833333333333333,
 1.382608695652174,
 1.3819095477386936,
 1.3799283154121864,
 1.3777793086436763,
 1.377755511022044,
 1.3769311534423279,
 1.3765690376569037,
 1.3733333333333333,
 1.3720316622691293,
 1.371308016877637,
 1.3706563706563706,
 1.3699059561128526,
 1.36986301369863,
 1.36986301369863,
 1.3669172932330826,
 1.3668341708542713,
 1.3666666666666667,
 1.3656597774244834,
 1.3625,
 1.3607142857142858,
 1.360601001669449,
 1.358974358974359,
 1.3581488933601609,
 1.3577023498694516,
 1.3567919661902883,
 1.3567567567567567,
 1.3544942408376963,
 1.3535353535353536,
 1.3527054108216432,
 1.3523809523809525,
 1.3513513513513513,
 1.3513513513513513,
 1.3513513513513513,
 1.3512784349408553,
 1.3511351135113512,
 1.35,
 1.35,
 1.3496143958868894,
 1.3488936041224613,
 1.348747591522158,
 1.3484646194926568,
 1.3484224965706446,
 1.3478260869565217,
 1.347764705882353,
 1.346683354192741,
 1.346,
 1.3454317897371715,
 1.3454317897371715,
 1.34518177028451,
 1.3445378151260505,
 1.3434343434343434,
 1.3421052631578947,
 1.342007434944238,
 1.3417085427135678,
 1.3416815742397137,
 1.3416666666666666,
 1.3396984924623117,
 1.3389121338912133,
 1.3378995433789955,
 1.3378248315688162,
 1.3363363363363363,
 1.3363028953229399,
 1.3358778625954197,
 1.335862796833773,
 1.335113484646195,
 1.3350125944584383,
 1.3344051446945338,
 1.3336666666666666,
 1.3333333333333333,
 1.3333333333333333,
 1.3333333333333333,
 1.3333333333333333,
 1.3333333333333333,
 1.3326653306613228,
 1.3321626626626626,
 1.3316645807259073,
 1.3316582914572865,
 1.3298379408960914,
 1.3294117647058823,
 1.3285714285714285,
 1.327713382507903,
 1.3276553106212425,
 1.3272727272727274,
 1.3268817204301075,
 1.3264750402447523,
 1.325678496868476,
 1.325088339222615,
 1.3250662533126656,
 1.3249211356466877,
 1.3242009132420092,
 1.3241525423728813,
 1.3232323232323233,
 1.3222222222222222,
 1.3221757322175731,
 1.322127659574468,
 1.321773611485517,
 1.321608040201005,
 1.3214304591863704,
 1.3213213213213213,
 1.3190797699424857,
 1.3176470588235294,
 1.3171759747102212,
 1.3166666666666667,
 1.3166023166023166,
 1.3165829145728642,
 1.316546762589928,
 1.3156666666666668,
 1.3152380952380953,
 1.3146613318090883,
 1.3141426783479349,
 1.3141426783479349,
 1.3140311804008908,
 1.3136320305052431,
 1.3133333333333332,
 1.3132420091324202,
 1.3131313131313131,
 1.312849162011173,
 1.3127413127413128,
 1.3121019108280254,
 1.3115577889447236,
 1.3107721639656815,
 1.3107721639656815,
 1.3095715756002397,
 1.3095238095238095,
 1.3095238095238095,
 1.3080808080808082,
 1.307352033468212,
 1.3072625698324023,
 1.3071895424836601,
 1.3071895424836601,
 1.306532663316583,
 1.306532663316583,
 1.3063063063063063,
 1.3061797752808988,
 1.3058333333333334,
 1.3054830287206267,
 1.30525,
 1.3045295295295296,
 1.3043478260869565,
 1.3043478260869565,
 1.3043478260869565,
 1.3033033033033032,
 1.3032581453634084,
 1.302367941712204,
 1.3017356475300401,
 1.3014460511679644,
 1.3013698630136987,
 1.3013698630136987,
 1.3013205282112845,
 1.301040832666133,
 1.301001301001301,
 1.301001301001301,
 1.3003250812703175,
 1.3001300130013,
 1.3,
 1.2994350282485876,
 1.2992213570634037,
 1.2975951903807614,
 1.297071129707113,
 1.297071129707113,
 1.297071129707113,
 1.2962956989247312,
 1.295947219604147,
 1.295812875196728,
 1.295,
 1.294290759270159,
 1.2941176470588236,
 1.2941176470588236,
 1.2937937937937938,
 1.2928232058014504,
 1.2921348314606742,
 1.2920353982300885,
 1.2908324552160169,
 1.2903225806451613,
 1.2893982808022924,
 1.288888888888889,
 1.288755536505215,
 1.2866333095067906,
 1.2862862862862863,
 1.2859185132237312,
 1.2857142857142858,
 1.2857142857142858,
 1.285425101214575,
 1.285140562248996,
 1.2849162011173185,
 1.2844611528822054,
 1.2842172139846353,
 1.2842105263157895,
 1.284153005464481,
 1.2831541218637992,
 1.282565130260521,
 1.2823529411764707,
 1.2820512820512822,
 1.2817089452603472,
 1.2814070351758795,
 1.2814070351758795,
 1.2813370473537604,
 1.2813370473537604,
 1.281081081081081,
 1.2809472551130248,
 1.2806236080178173,
 1.2800808897876643,
 1.28,
 1.279199110122358,
 1.2784810126582278,
 1.2784810126582278,
 1.2783053323593865,
 1.2777777777777777,
 1.277533039647577,
 1.2774468085106383,
 1.2764830508474576,
 1.2762762762762763,
 1.2761506276150627,
 1.276113669064748,
 1.2754666666666667,
 1.2750455373406193,
 1.275035700999628,
 1.2741935483870968,
 1.274131274131274,
 1.274,
 1.2736966824644549,
 1.2736842105263158,
 1.2727272727272727,
 1.2727272727272727,
 1.2727272727272727,
 1.2718600953895072,
 1.2717919405544442,
 1.2717678100263852,
 1.271356783919598,
 1.27,
 1.27,
 1.2695652173913043,
 1.2692692692692693,
 1.2687813021702838,
 1.2680115273775217,
 1.2670986321094313,
 1.2667959949937422,
 1.2666666666666666,
 1.26666,
 1.2665330661322645,
 1.2658898305084745,
 1.2657303370786517,
 1.2654502648616834,
 1.2652329749103943,
 1.2650602409638554,
 1.2650300601202404,
 1.2644889357218125,
 1.2642642642642643,
 1.2639766650461837,
 1.263316582914573,
 1.2631315657828914,
 1.263125,
 1.2625698324022345,
 1.2625260521042083,
 1.2625250501002003,
 1.2615643397813288,
 1.2609756097560976,
 1.2602739726027397,
 1.26,
 1.2595063375583722,
 1.2594004533040741,
 1.2593844870725606,
 1.2589413447782547,
 1.2585604311008467,
 1.2584269662921348,
 1.2583752093802345,
 1.258129064532266,
 1.2578616352201257,
 1.2575150300601203,
 1.2575150300601203,
 1.2573103448275862,
 1.257286432160804,
 1.2571428571428571,
 1.2571428571428571,
 1.2566137566137565,
 1.256281407035176,
 1.256281407035176,
 1.256281407035176,
 1.256281407035176,
 1.256281407035176,
 1.2562562562562563,
 1.2560386473429952,
 1.256,
 1.2557959814528594,
 1.2557781201848999,
 1.2557077625570776,
 1.255639097744361,
 1.2553648068669527,
 1.2553191489361701,
 1.2552301255230125,
 1.2548262548262548,
 1.2547528517110267,
 1.2546024819309969,
 1.2539888651476876,
 1.253615127919911,
 1.2532290362953693,
 1.2532188841201717,
 1.2531328320802004,
 1.2530311457174639,
 1.2528,
 1.252723311546841,
 1.2526315789473683,
 1.2526315789473683,
 1.2526096033402923,
 1.2525252525252526,
 1.2525252525252526,
 1.252408477842004,
 1.2520868113522539,
 1.2520868113522539,
 1.2520868113522539,
 1.2520473157415832,
 1.251840942562592,
 1.2518292520317615,
 1.251472320376914,
 1.2512512512512513,
 1.2510425354462051,
 1.2509622786759045,
 1.2508960573476702,
 1.2507817385866167,
 1.2506253126563283,
 1.2503576537911303,
 1.2501562695336916,
 1.25,
 1.25,
 1.25,
 1.25,
 1.2485414235705952,
 1.2480739599383668,
 1.248,
 1.2470771628994544,
 1.2469018112488084,
 1.2468619246861925,
 1.2468619246861925,
 1.2462462462462462,
 1.2461538461538462,
 1.2458286985539488,
 1.2456236559139784,
 1.2452830188679245,
 1.2452830188679245,
 1.2450928742994396,
 1.2446351931330473,
 1.2444444444444445,
 1.2439156300703083,
 1.2437611408199643,
 1.2432432432432432,
 1.2432045779685266,
 1.2428571428571429,
 1.2426516572858037,
 1.242304104477612,
 1.2422845691382765,
 1.2420091324200913,
 1.2407407407407407,
 1.240677966101695,
 1.240506329113924,
 1.2402570044238466,
 1.2401055408970976,
 1.24,
 1.239841633673682,
 1.23941493456505,
 1.2393822393822393,
 1.2391304347826086,
 1.2390265585065008,
 1.2384937238493723,
 1.2384615384615385,
 1.2382308362369339,
 1.2380952380952381,
 1.237926972909305,
 1.2376547068383548,
 1.237491661107405,
 1.2367688022284122,
 1.2367491166077738,
 1.2360211889346675,
 1.2358908415487926,
 1.2358024691358025,
 1.2357449990652458,
 1.2355212355212355,
 1.2352380952380952,
 1.2352352352352352,
 1.2351351351351352,
 1.235001235001235,
 1.2349799732977302,
 1.2346938775510203,
 1.23463687150838,
 1.2342483227566035,
 1.2342391304347826,
 1.2341708542713568,
 1.2340552856767983,
 1.2339431754716108,
 1.2338530066815145,
 1.2334868339171097,
 1.2333333333333334,
 1.2333333333333334,
 1.2333333333333334,
 1.2328767123287672,
 1.2326656394453004,
 1.23265408176022,
 1.2325581395348837,
 1.232185273159145,
 1.2321212121212122,
 1.231970909090909,
 1.23125,
 1.2311780336581044,
 1.231001231001231,
 1.2307692307692308,
 1.2304878149566711,
 1.2304609218436873,
 1.2301255230125523,
 1.23,
 1.23,
 1.229050279329609,
 1.2285714285714286,
 1.2283894449499546,
 1.2283894449499546,
 1.2283894449499546,
 1.2280701754385965,
 1.2280701754385965,
 1.2279816276300866,
 1.227928870292887,
 1.2278360343183985,
 1.2278260869565218,
 1.2275,
 1.2274549098196392,
 1.2274549098196392,
 1.2274549098196392,
 1.2274247491638797,
 1.2272727272727273,
 1.2272727272727273,
 1.2272727272727273,
 1.2269938650306749,
 1.2269129287598945,
 1.226478494623656,
 1.2264150943396226,
 1.2262262262262262,
 1.2261306532663316,
 1.2258064516129032,
 1.2258064516129032,
 1.2256267409470751,
 1.2252873563218392,
 1.2252042007001167,
 1.225122512251225,
 1.225122512251225,
 1.225,
 1.2249443207126949,
 1.2249443207126949,
 1.2243589743589745,
 1.224,
 1.2239020878329734,
 1.2237762237762237,
 1.2231020408163265,
 1.223069590085796,
 1.2229005538602982,
 1.2228152101400933,
 1.222444889779559,
 1.2223393045310853,
 1.222222901234945,
 1.2222222222222223,
 1.2222222222222223,
 1.221818181818182,
 1.221774193548387,
 1.2217573221757323,
 1.2214297928583644,
 1.2212212212212212,
 1.2212212212212212,
 1.220440881763527,
 1.2203791469194314,
 1.2202753441802252,
 1.2201117318435755,
 1.22007722007722,
 1.22,
 1.2196647485614212,
 1.2191780821917808,
 1.2191666666666667,
 1.2187715665976535,
 1.2186379928315412,
 1.2186379928315412,
 1.2186379928315412,
 1.2185792349726776,
 1.2184508268059182,
 1.218274111675127,
 1.2180284210526315,
 1.2177359031082393,
 1.217410964288323,
 1.2173913043478262,
 1.216931216931217,
 1.2166666666666666,
 1.2160804020100502,
 1.2160228898426324,
 1.216,
 1.215443279313632,
 1.2151735962280326,
 1.2151536812008576,
 1.214960294596558,
 1.2149255014480607,
 1.2147195426938193,
 1.2144592084583512,
 1.214329083181542,
 1.2138970280452073,
 1.213875968992248,
 1.2138728323699421,
 1.2137931034482758,
 1.2137850779510022,
 1.2137137137137137,
 1.213389121338912,
 1.213389121338912,
 1.2133468149646107,
 1.2131979695431472,
 1.2131901840490797,
 1.2130838922226144,
 1.213032581453634,
 1.21301775147929,
 1.2129386592661235,
 1.2124711316397228,
 1.212135759205031,
 1.2121212121212122,
 1.21203007518797,
 1.2112112112112112,
 1.2111637704054765,
 1.2111637704054765,
 1.2110726643598615,
 1.2109479305740989,
 1.2106768350810295,
 1.2102689486552567,
 1.2101728818402628,
 1.209688581314879,
 1.2095808383233533,
 1.209090909090909,
 1.2089810017271156,
 1.208888888888889,
 1.2087912087912087,
 1.208695652173913,
 1.208585121900396,
 1.2082405345211582,
 1.2080536912751678,
 1.2080200501253133,
 1.208,
 1.2079505300353357,
 1.2077596996245306,
 1.2077596996245306,
 1.2073578595317727,
 1.2073153307615374,
 1.207120712071207,
 1.2068045363575717,
 1.2067039106145252,
 1.2066791320607035,
 1.206318812829105,
 1.2062062062062062,
 1.2060301507537687,
 1.2058823529411764,
 1.205813953488372,
 1.2057465366854798,
 1.2057465366854798,
 1.2056367432150312,
 1.2055837563451777,
 1.2053571428571428,
 1.2048716833405828,
 1.2048192771084338,
 1.2048192771084338,
 1.2046822742474916,
 1.2046549686335122,
 1.2045959970348405,
 1.2043010752688172,
 1.2041984732824427,
 1.2036363636363636,
 1.2035619339259733,
 1.2033898305084745,
 1.2030075187969924,
 1.202970297029703,
 1.2028588807785887,
 1.2028070175438597,
 1.2026726057906458,
 1.2025316455696202,
 1.202503128911139,
 1.2024048096192386,
 1.2024048096192386,
 1.202136181575434,
 1.2021108179419524,
 1.201848998459168,
 1.201834862385321,
 1.2016,
 1.2013348164627364,
 1.2013105205678922,
 1.2012022022022022,
 1.2012012012012012,
 1.2012012012012012,
 1.2012012012012012,
 1.2012012012012012,
 1.2010919017288444,
 1.2010443864229765,
 1.200800533689126,
 1.200800533689126,
 1.2006003001500751,
 1.200527704485488,
 1.2004801920768307,
 1.2002688602246903,
 1.2002400480096018,
 1.200150018752344,
 1.2001200120012,
 1.2000800053336889,
 1.2000240004800096,
 1.2000060000300001,
 1.2000030000075,
 1.2000021818221487,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.199090909090909,
 1.1984732824427482,
 1.198257080610022,
 1.198140200286123,
 1.197592778335005,
 1.196911196911197,
 1.1968900861494145,
 1.1967798194829011,
 1.19625,
 1.195994277539342,
 1.1959153595115275,
 1.1956521739130435,
 1.195360281195079,
 1.1952440550688361,
 1.1952380952380952,
 1.1951083935519733,
 1.195001195001195,
 1.1949685534591195,
 1.1949265687583444,
 1.1947115384615385,
 1.1945187700568036,
 1.1939953810623556,
 1.1938775510204083,
 1.193757460984131,
 1.1936936936936937,
 1.1936560934891485,
 1.1936560934891485,
 1.1936560934891485,
 1.1934156378600822,
 1.193225558121632,
 1.1930783242258651,
 1.1925925925925926,
 1.1924911524849977,
 1.1918951132300357,
 1.1914893617021276,
 1.191149295774648,
 1.1910112359550562,
 1.190909090909091,
 1.190909090909091,
 1.19072708113804,
 1.1904761904761905,
 1.1904761904761905,
 1.1904761904761905,
 1.190238047609522,
 1.1902113459399333,
 1.1902113459399333,
 1.189482470784641,
 1.1894736842105262,
 1.1893337297779099,
 1.1891891891891893,
 1.1889862327909888,
 1.1889862327909888,
 1.1889862327909888,
 1.1888888888888889,
 1.1887608069164266,
 1.1886886886886887,
 1.188490408673895,
 1.1882510013351135,
 1.1882426516572857,
 1.188235294117647,
 1.1882240762812872,
 1.1881785283474064,
 1.1880687563195147,
 1.1879895561357703,
 1.1879699248120301,
 ...]

In [40]:
sold[(sold["ClosePrice"] / sold["OriginalListPrice"]) == np.inf]

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed,list_after_close_flag,purchase_after_close_flag,negative_time_flag,coord_missing,coord_invalid
202991,CaliforniaDesert,CaliforniaDesert,"Carpet,Tile",True,True,0.0,1100767901,larrylopeztamariskrealty@gmail.com,2025-02-06,1905000.0,...,NaN,NaN,NaN,2025-02,6.8425,False,False,False,False,False
356860,InlandValleys,InlandValleys,"Carpet,Tile,Vinyl",True,False,0.0,1120337594,acosta4homes@gmail.com,2025-12-29,267900.0,...,NaN,NaN,NaN,2025-12,6.1900,False,False,False,False,False

In [43]:
(sold["OriginalListPrice"] == sold["ListPrice"]).mean()

np.float64(0.6884910560141595)

In [44]:
sold[sold["OriginalListPrice"] != sold["ListPrice"]][["OriginalListPrice", "ListPrice"]]

        OriginalListPrice  ListPrice
0                499000.0   295000.0
2                739900.0   770000.0
3                     NaN   858000.0
7                     NaN  2340000.0
11                    NaN  2150000.0
...                   ...        ...
413567           649800.0   599800.0
413568           459000.0   420000.0
413569           279000.0   215000.0
413570           449000.0   419000.0
413571          1579000.0  1399999.0

[128832 rows x 2 columns]

In [46]:
sorted(sold["OriginalListPrice"] / sold["ListPrice"])

[0.0,
 1.2121212121212122e-07,
 5.555555555555555e-07,
 6.666671111114074e-07,
 9.747606614447347e-07,
 1e-06,
 1e-06,
 1.0195412064570943e-06,
 1.057377049180328e-06,
 9.75609756097561e-06,
 1.001669449081803e-05,
 0.00010507004669779854,
 0.0001051585976627713,
 0.00010721229449606862,
 0.00031746031746031746,
 0.000925925925925926,
 0.0009987998399786637,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.001,
 0.0010094339622641509,
 0.0010144927536231885,
 0.0010152284263959391,
 0.0010198019801980198,
 0.0010204498977505112,
 0.0010256673511293635,
 0.0010454870207192188,
 0.001056,
 0.00106,
 0.0010635930047694754,
 0.0010770416024653312,
 0.0010836945648549517,
 0.0010914105594956658,
 0.0010955555555555556,
 0.0011176470588235294,
 0.0011343283582089553,
 0.0012129032258064516,
 0.00125,
 0.0014075116675309283,
 0.0014718181818181818,
 0.003380524933492461,
 0.005590794979079498,
 0.009999266666123456,
 0.01,
 0.01000398406374502,
 0.010217864923747277,
 0.013300550091681946,
 0.02644411102775694,
 0.05774593533448548,
 0.09316770186335403,
 0.09433620504228318,
 0.09473684210526316,
 0.09895615866388309,
 0.09966654316413487,
 0.09982617333002235,
 0.09988748593574197,
 0.09995967819358308,
 0.09997999955554568,
 0.09998999988888765,
 0.09999299838962962,
 0.09999437496484354,
 0.09999849999749999,
 0.09999871428387755,
 0.09999887499859375,
 0.0999989998599804,
 0.0999993333328395,
 0.09999946627099557,
 0.0999997187499121,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.10011778563015312,
 0.1002785848368545,
 0.10087912087912088,
 0.10091743119266056,
 0.10185752194325373,
 0.10199897488467452,
 0.10223431970244444,
 0.10240963855421686,
 0.10244988864142539,
 0.10256410256410256,
 0.1029940119760479,
 0.1034319526627219,
 0.10348128807658834,
 0.10426086956521739,
 0.10434764460069292,
 0.10474934036939314,
 0.10512820512820513,
 0.10566037735849057,
 0.1058139534883721,
 0.10588235294117647,
 0.10714285714285714,
 0.10725229826353422,
 0.10727272727272727,
 0.10751879699248121,
 0.10949771689497717,
 0.11018363939899833,
 0.11022044088176353,
 0.1112267597297904,
 0.11557788944723618,
 0.12854030501089325,
 0.1517664913704867,
 0.27219796215429404,
 0.2752572836642992,
 0.3311671924290221,
 0.3377049180327869,
 0.3389830440677966,
 0.4184168012924071,
 0.4373593398349587,
 0.4411761764705882,
 0.45165201576235225,
 0.458,
 0.46308724832214765,
 0.4959661420447031,
 0.5070422535211268,
 0.5238095238095238,
 0.525065963060686,
 0.5427531837477259,
 0.5448997384481256,
 0.5642701525054467,
 0.5720164609053497,
 0.5727272727272728,
 0.5761904761904761,
 0.5866115482064275,
 0.5866666666666667,
 0.6025466120964075,
 0.6052631578947368,
 0.6078431372549019,
 0.6179775280898876,
 0.6219281663516069,
 0.6353790613718412,
 0.6451596774193549,
 0.6474405191059841,
 0.6491166511693187,
 0.6515679442508711,
 0.6541353383458647,
 0.655664262295082,
 0.6576923076923077,
 0.6582278481012658,
 0.658703071672355,
 0.6666666666666666,
 0.6842465753424658,
 0.6869565217391305,
 0.6880131362889984,
 0.7,
 0.7009428403064231,
 0.7014028056112225,
 0.7128571428571429,
 0.7139682539682539,
 0.7142857142857143,
 0.7147962830593281,
 0.7169230769230769,
 0.71875,
 0.7199104,
 0.7200709429500444,
 0.7228915662650602,
 0.7268292682926829,
 0.7311653116531165,
 0.7326158940397351,
 0.7333333333333333,
 0.7350565428109854,
 0.7352941176470589,
 0.737350233706856,
 0.7376967213114755,
 0.7391304347826086,
 0.74,
 0.74,
 0.7405485544848036,
 0.7407407407407407,
 0.7414285714285714,
 0.741930488977206,
 0.7436031066085342,
 0.743801652892562,
 0.746394298221,
 0.7468658308882369,
 0.7492477432296891,
 0.7499374843710928,
 0.7499374843710928,
 0.75,
 0.75,
 0.750501002004008,
 0.7516650808753568,
 0.7526881720430108,
 0.7539622641509434,
 0.7564066193853428,
 0.7571428571428571,
 0.7573033707865169,
 0.7575757575757576,
 0.7583547557840618,
 0.7619047619047619,
 0.7636085103188437,
 0.764102564102564,
 0.7660151395322562,
 0.7666666666666667,
 0.767948717948718,
 0.7701149425287356,
 0.7741077423686793,
 0.7748049052396878,
 0.7751937984496124,
 0.775550066065376,
 0.7756211180124224,
 0.7760869565217391,
 0.7770256756756757,
 0.7777283840853523,
 0.7777777777777778,
 0.7777777777777778,
 0.7786885245901639,
 0.7803921568627451,
 0.7808695652173913,
 0.7814207650273224,
 0.7823529411764706,
 0.7859611805370912,
 0.7867730900798175,
 0.7871621621621622,
 0.7909372712402057,
 0.7913431356352222,
 0.7915897435897435,
 0.7918138120667424,
 0.7926311423813523,
 0.7938144329896907,
 0.7942857142857143,
 0.7945859872611465,
 0.7953615279672579,
 0.7954545454545454,
 0.7960199004975125,
 0.7963636363636364,
 0.799,
 0.7991360691144709,
 0.7992,
 0.7998285469352765,
 0.7999992,
 0.8023456790123457,
 0.8043933054393305,
 0.8061389337641357,
 0.8064516129032258,
 0.8074534161490683,
 0.8076923076923077,
 0.8083140877598153,
 0.8094971428571428,
 0.81249875,
 0.8127272727272727,
 0.812773951158422,
 0.8128474366893144,
 0.8131868131868132,
 0.8145363408521303,
 0.8148148148148148,
 0.8154105736782902,
 0.8164556962025317,
 0.8165137614678899,
 0.8178260869565217,
 0.8182230514212503,
 0.8194899817850637,
 0.8207142857142857,
 0.8209677419354838,
 0.8211961209713255,
 0.8224314437970912,
 0.822875294117647,
 0.8232467198353486,
 0.8241379310344827,
 0.8244829513694801,
 0.8247078464106845,
 0.8252581413820492,
 0.8253968253968254,
 0.8260869565217391,
 0.8260869565217391,
 0.8262068965517242,
 0.8266666666666667,
 0.8274137931034483,
 0.8275564752543542,
 0.8285714285714286,
 0.8286792452830188,
 0.8291666666666667,
 0.8291666666666667,
 0.8302767589196399,
 0.8308270676691729,
 0.8327137546468402,
 0.8327759197324415,
 0.8327759197324415,
 0.8329061951060638,
 0.8329214814814815,
 0.8330550918196995,
 0.8330550918196995,
 0.8331914893617022,
 0.8331943286071727,
 0.8331943286071727,
 0.83325,
 0.8332638599416423,
 0.8333177763257904,
 0.8333316666666667,
 0.833332777775926,
 0.833332777775926,
 0.8333333333333334,
 0.8333333333333334,
 0.8333333333333334,
 0.8333333333333334,
 0.8343966623876765,
 0.8350785340314136,
 0.8353760445682451,
 0.8356164383561644,
 0.8358492675835849,
 0.8372660699755899,
 0.8375,
 0.8379970544918999,
 0.8384146341463414,
 0.8384353741496599,
 0.8385806451612903,
 0.8386836586546217,
 0.84,
 0.8401478991596638,
 0.8401869158878504,
 0.8403597526700394,
 0.8409090909090909,
 0.8419873684210526,
 0.8421052631578947,
 0.84321608040201,
 0.84375,
 0.846,
 0.8465597883597884,
 0.8466101694915255,
 0.8466101694915255,
 0.8468052347959969,
 0.847457627118644,
 0.8478260869565217,
 0.8483333333333334,
 0.8484566412327845,
 0.8492663829787234,
 0.849624060150376,
 0.849714648065948,
 0.8499249624812406,
 0.849999,
 0.85,
 0.8507014084507042,
 0.8510531914893616,
 0.8511627906976744,
 0.8513011152416357,
 0.8514814814814815,
 0.8517034068136272,
 0.8524348253812101,
 0.8535714285714285,
 0.8538461538461538,
 0.8542332940582393,
 0.8542332940582393,
 0.8547619047619047,
 0.8548387096774194,
 0.8552380952380952,
 0.8552529182879377,
 0.8552631578947368,
 0.8553132955350049,
 0.8557436579715266,
 0.8561904761904762,
 0.8562129260036307,
 0.8564285714285714,
 0.8566308243727598,
 0.8569384835479256,
 0.8570788571428571,
 0.8571224460637233,
 0.8571292504048005,
 0.8571428571428571,
 0.8571428571428571,
 0.8571428571428571,
 0.8571428571428571,
 0.8576271186440678,
 0.8579717301401149,
 0.8582089552238806,
 0.8590909090909091,
 0.859375,
 0.8598130841121495,
 0.8620672413793103,
 0.8620689655172413,
 0.8623727272727273,
 0.8626198083067093,
 0.8627639155470249,
 0.8629441624365483,
 0.8635122838944495,
 0.8635561312607944,
 0.8635561312607944,
 0.8636363636363636,
 0.8637837837837837,
 0.8641975308641975,
 0.8642770306756261,
 0.8643243243243244,
 0.8644986449864499,
 0.8648648648648649,
 0.8652173913043478,
 0.8653333333333333,
 0.8653944937514474,
 0.8657718120805369,
 0.8664627930682977,
 0.8664886515353805,
 0.8664886515353805,
 0.86666,
 0.8666666666666667,
 0.8666666666666667,
 0.8669354838709677,
 0.8672566371681416,
 0.8677286956521739,
 0.8678260869565217,
 0.8679245283018868,
 0.8681159420289855,
 0.8686956521739131,
 0.868995633187773,
 0.8690909090909091,
 0.8691301000769823,
 0.869167429094236,
 0.8694678260869565,
 0.8695644927536232,
 0.869837296620776,
 0.8705882352941177,
 0.8709674141515021,
 0.8709677419354839,
 0.8717948717948718,
 0.8722222222222222,
 0.8729662077596996,
 0.8731778425655977,
 0.8732572877059569,
 0.8740740740740741,
 0.8742138364779874,
 0.874296435272045,
 0.8748435544430538,
 0.8748435544430538,
 0.8748957464553795,
 0.874982497549657,
 0.8749843730466308,
 0.8749843730466308,
 0.8749996874992187,
 0.875,
 0.875,
 0.8752188047011753,
 0.8758758758758759,
 0.5714285714285714,
 0.5812005583992554,
 0.5913792250210324,
 0.6012024048096193,
 0.6226415094339622,
 0.625,
 0.6427442486682667,
 0.6505181262462816,
 0.6529850746268657,
 0.6551059730250481,
 0.6554375686561699,
 0.655829210836278,
 0.6618962432915921,
 0.6666666666666666,
 0.6666666666666666,
 0.68,
 0.6862068965517242,
 0.6885245901639344,
 0.6939130434782609,
 0.6941525972116007,
 0.6954612005856515,
 0.6957141335713525,
 0.6985294117647058,
 0.7004680187207488,
 0.7017543859649122,
 0.7079646017699115,
 0.7104270769230769,
 0.7172140430351076,
 0.7173289183222958,
 0.7327349331379374,
 0.736,
 0.7361180058151904,
 0.7373737373737373,
 0.7382716049382716,
 0.7392592592592593,
 0.746268656716418,
 0.7499987499937499,
 0.7514450867052023,
 0.7525083612040134,
 0.7541212629226041,
 0.7696917808219178,
 0.7697051455000964,
 0.770042194092827,
 0.7704818052449685,
 0.7722222222222223,
 0.7753424657534247,
 0.7777777777777778,
 0.7777777777777778,
 0.7833333333333333,
 0.7834645669291339,
 0.7842857142857143,
 0.7858472998137802,
 0.7860494610019023,
 0.7893692978976596,
 0.7894736842105263,
 0.7942857142857143,
 0.7956363636363636,
 0.7959183673469388,
 0.7983193277310925,
 0.7993496816149573,
 0.79992,
 0.7999992,
 0.8,
 0.8034042553191489,
 0.8079676767676768,
 0.8089329642110783,
 0.809375,
 0.8108108108108109,
 0.8125,
 0.8142857142857143,
 0.8151658767772512,
 0.8163553048995418,
 0.8172727272727273,
 0.8181447858472998,
 0.8188524590163935,
 0.8225602027883396,
 0.8235190305312077,
 0.8235294117647058,
 0.8238532110091743,
 0.8259355961705831,
 0.827583234193693,
 0.8305555555555556,
 0.83125,
 0.8319327731092437,
 0.8325,
 0.8331943286071727,
 0.83333125,
 0.8333320512820512,
 0.8333330555550926,
 0.8333333333333334,
 0.8333333333333334,
 0.8333455557592626,
 0.837125748502994,
 0.8376865671641791,
 0.8377622377622378,
 0.8381052631578947,
 0.8383233532934131,
 0.838655462184874,
 0.8396946564885496,
 0.8399359743897559,
 0.8412698412698413,
 0.8417061611374408,
 0.8420886409095695,
 0.8428290766208252,
 0.8438408003479774,
 0.8444444444444444,
 0.8449612403100775,
 0.8455598455598455,
 0.8457627118644068,
 0.8461538461538461,
 0.8465608062483869,
 0.847457627118644,
 0.8475030842675535,
 0.8484848484848485,
 0.8501700340068014,
 0.8508359195114626,
 0.8518515775029213,
 0.8528571428571429,
 0.855599529361429,
 0.8557936796222303,
 0.8560606060606061,
 0.856326530612245,
 0.8567335243553008,
 0.8570476190476191,
 0.8571425714285714,
 0.8571428571428571,
 0.8582278481012658,
 0.8587786259541985,
 0.8593530239099859,
 0.8594179211469534,
 0.8608,
 0.861244019138756,
 0.8620303448275862,
 0.8620689655172413,
 0.8620689655172413,
 0.8636363636363636,
 0.8643598615916955,
 0.8648444088835067,
 0.8652173913043478,
 0.8654545454545455,
 0.8662207357859532,
 0.8665616367754198,
 0.8666665777777185,
 0.8679553945431903,
 0.8695630434782609,
 0.8695652173913043,
 0.8700401767047831,
 0.8704858251970357,
 0.871264367816092,
 0.8713868613138687,
 0.8730142857142857,
 0.8738592324040505,
 0.8742857142857143,
 0.8748435544430538,
 0.8749843730466308,
 0.875,
 0.8751458576429405,
 0.875422138836773,
 0.8759964570416298,
 0.8760951188986232,
 0.8771921052631579,
 0.8771929824561403,
 0.8775510204081632,
 0.8777777777777778,
 0.8787878787878788,
 0.8787878787878788,
 0.8788235294117647,
 0.8789237288101391,
 0.878987898789879,
 0.879,
 0.8799039231385108,
 0.88,
 0.8800035200140801,
 0.8805018867924528,
 0.8805791909240185,
 0.8806767586821015,
 0.8809240295308407,
 0.8809523809523809,
 0.8809523809523809,
 0.8810214741729542,
 0.8811764705882353,
 0.8812260536398467,
 0.8814218009478673,
 0.8814852492370295,
 0.8815637319316688,
 0.8817647058823529,
 0.8820588988476312,
 0.8822143698468787,
 0.8822143698468787,
 0.8823529411764706,
 0.8823529411764706,
 0.8823529411764706,
 0.8823585813546919,
 0.8826086956521739,
 0.8831858407079646,
 0.8832558139534884,
 0.8833333333333333,
 0.8833910482921083,
 0.8835443037974684,
 0.8838174273858921,
 0.8839050131926122,
 0.8842975206611571,
 0.8844672657252889,
 0.8845265588914549,
 0.8846153846153846,
 0.8852295081967213,
 0.8857142857142857,
 0.8857868020304569,
 0.8859315589353612,
 0.886075805159247,
 0.8860759493670886,
 0.8861047835990888,
 0.8865777777777778,
 0.8870967741935484,
 0.8872614292055038,
 0.8874074074074074,
 0.8877777777777778,
 0.8878103416091095,
 0.8878504672897196,
 0.888065233506301,
 0.8884758364312267,
 0.8887407407407407,
 0.8887652947719689,
 0.8888148148148148,
 0.8888641920426762,
 0.8888641920426762,
 0.8888866666666667,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8888888888888888,
 0.8889135809328037,
 0.8890322580645161,
 0.88961618565903,
 0.8896946032631432,
 0.8897126969416126,
 0.8904108087819298,
 0.8904109589041096,
 0.8904458598726115,
 0.890538253718493,
 0.8905579399141631,
 0.890625,
 0.8908663697104677,
 0.8909090909090909,
 0.8909090909090909,
 0.8909090909090909,
 0.8910714285714286,
 0.8910891089108911,
 0.8912655971479501,
 0.8913043478260869,
 0.8914295902052459,
 0.8914728682170543,
 0.8916815280254671,
 0.8917550302591424,
 0.8919642857142858,
 0.8919642857142858,
 0.8920863309352518,
 0.8923643054277829,
 0.8927374301675978,
 0.8927805575411007,
 0.8928214285714285,
 0.8928553571428571,
 0.892856760202715,
 0.8928571428571429,
 0.8928571428571429,
 0.8928571428571429,
 0.8928571428571429,
 0.8928571428571429,
 0.893042654028436,
 0.8931071972167862,
 0.8931552587646077,
 0.8931552587646077,
 0.8936170212765957,
 0.8936170212765957,
 0.8938271604938272,
 0.8938536312849162,
 0.8938547486033519,
 0.8939072446195817,
 0.8939393939393939,
 0.8939393939393939,
 0.894134477825465,
 0.8941798941798942,
 0.8942307692307693,
 0.8943089430894309,
 0.8944,
 0.8945147679324894,
 0.8945981554677207,
 0.8947244306697211,
 0.8947368421052632,
 0.8948717948717949,
 0.8949818934299018,
 0.8952173913043479,
 0.8953731343283582,
 0.8954154727793696,
 0.8954248366013072,
 0.8955222321227345,
 0.8955223880597015,
 0.8957575757575758,
 0.89584,
 0.8961538461538462,
 0.8964137931034483,
 0.8964858526252081,
 0.8965445892820194,
 0.896551724137931,
 0.8968253968253969,
 0.8969406060012367,
 0.896969696969697,
 0.8974358974358975,
 0.8974358974358975,
 0.8974358974358975,
 0.8974358974358975,
 0.8974489795918368,
 0.8977272727272727,
 0.8979591836734694,
 0.898,
 0.8983834913905994,
 0.8984375,
 0.8986846068882418,
 0.89875,
 0.8988650410158445,
 0.8988763135966864,
 0.899035684558215,
 0.8990733094779337,
 0.8990825688073395,
 0.8997995991983968,
 0.8998998998998999,
 0.8999799959991999,
 0.8999799959991999,
 0.8999899989999,
 0.899999,
 0.8999998999999,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9000009000009,
 0.9000160003200064,
 0.9004739336492891,
 0.9006024096385542,
 0.9007518796992481,
 0.9008016032064128,
 0.9008016032064128,
 0.9010891089108911,
 0.9013953488372093,
 0.9015317286652079,
 0.9016393442622951,
 0.9016949152542373,
 0.9016949152542373,
 0.9017034068136273,
 0.9018016032064128,
 0.9018036072144289,
 0.9019354838709678,
 0.9019607843137255,
 0.9021739130434783,
 0.9022041781169274,
 0.9022481203007519,
 0.9025,
 0.9025641025641026,
 0.9025806451612903,
 0.9025806451612903,
 0.9025821596244131,
 0.9026128266033254,
 0.9028925619834711,
 0.903010033444816,
 0.9030694668820679,
 0.9031578947368422,
 0.9031612903225806,
 0.9032251612903226,
 0.9032258064516129,
 0.9035087719298246,
 0.9035175879396985,
 0.9035409035409036,
 0.9038095238095238,
 0.9038095238095238,
 0.9039780521262003,
 0.9039943938332166,
 0.9040333796940194,
 0.9040909090909091,
 0.9042553191489362,
 0.9045454545454545,
 0.9045454545454545,
 0.9046711153479504,
 0.9047609523809523,
 0.9047619047619048,
 0.9047619047619048,
 0.9047619047619048,
 0.9047619047619048,
 0.9050724637681159,
 0.9050847457627119,
 0.9051724137931034,
 0.9054716981132076,
 0.9055849056603773,
 0.905625,
 0.905625,
 0.9060402684563759,
 0.9061855670103093,
 0.90625,
 0.90625,
 0.9063444108761329,
 0.9065420560747663,
 0.9066652839301323,
 0.9067115833117388,
 0.906816760475297,
 0.9068185940084518,
 0.9069767441860465,
 0.907024323709934,
 0.9070764832022874,
 0.9072727272727272,
 0.9073057202080076,
 0.9078341013824884,
 0.9078826161337018,
 0.908080808080808,
 0.9081818181818182,
 0.9081818181818182,
 0.9081818181818182,
 0.9083275017494752,
 0.9083916083916084,
 0.9084848484848485,
 0.9084848484848485,
 0.9086124401913875,
 0.9087272727272727,
 0.9088607594936708,
 0.9088636363636363,
 0.908883826879271,
 0.9089253187613844,
 0.9089253187613844,
 0.9089253187613844,
 0.9089393939393939,
 0.9089393939393939,
 0.9089393939393939,
 0.908951048951049,
 0.908961038961039,
 0.9089805825242718,
 0.9089805825242718,
 0.9090230303030303,
 0.9090690909090909,
 0.9090702432370994,
 0.9090743771594836,
 0.9090743771594836,
 0.9090743771594836,
 0.9090743771594836,
 0.9090816519500168,
 0.9090816519500168,
 0.9090853991150979,
 0.9090883116883117,
 0.909089090909091,
 0.909089090909091,
 0.909089090909091,
 0.9090892561983471,
 0.9090896103896103,
 0.9090896103896103,
 0.909089696969697,
 0.9090897727272728,
 0.90909,
 0.90909,
 0.90909,
 0.90909,
 0.90909,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090909090909091,
 0.9090919716674589,
 0.9091099558471347,
 0.9092380432805964,
 0.9092544098927078,
 0.9095038653933606,
 0.9098131211925803,
 0.9099089989888777,
 0.9099171974522293,
 0.909919028340081,
 0.910250569476082,
 0.9103343465045592,
 0.910355486862442,
 ...]

In [49]:
(sold["ListPrice"] <= 0).sum()

np.int64(0)