In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
listed = pd.read_csv("listed_final.csv", low_memory=False)
sold = pd.read_csv("sold_final.csv", low_memory=False)

In [4]:
listed.shape, sold.shape

((540318, 62), (396721, 69))

In [5]:
date_cols = ["CloseDate", "PurchaseContractDate", "ListingContractDate", "ContractStatusChangeDate"]
for df in [listed, sold]:
    for col in date_cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

In [6]:
sold[date_cols].info()

<class 'pandas.DataFrame'>
RangeIndex: 396721 entries, 0 to 396720
Data columns (total 4 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CloseDate                 396721 non-null  datetime64[us]
 1   PurchaseContractDate      396527 non-null  datetime64[us]
 2   ListingContractDate       396720 non-null  datetime64[us]
 3   ContractStatusChangeDate  396132 non-null  datetime64[us]
dtypes: datetime64[us](4)
memory usage: 12.1 MB

In [7]:
main_fields = ["ListingKey", "ListingContractDate", "ListPrice", "ClosePrice",
               "PurchaseContractDate", "CloseDate", "LivingArea", "BedroomsTotal",
               "BathroomsTotalInteger", "Latitude", "Longitude", "UnparsedAddress"]

In [8]:
listed["list_after_close_flag"] = df["CloseDate"] < df["ListingContractDate"]
listed["purchase_after_close_flag"] = df["PurchaseContractDate"] < df["ListingContractDate"]

In [9]:
listed["list_after_close_flag"] & listed["purchase_after_close_flag"]

0         False
1         False
2         False
3         False
4         False
          ...
540313    False
540314    False
540315    False
540316    False
540317    False
Length: 540318, dtype: bool

In [10]:
listed.info()

<class 'pandas.DataFrame'>
RangeIndex: 540318 entries, 0 to 540317
Data columns (total 64 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   OriginalListPrice            539549 non-null  float64
 1   ListingKey                   540318 non-null  int64
 2   ListAgentEmail               493109 non-null  str
 3   CloseDate                    163479 non-null  datetime64[us]
 4   ClosePrice                   143182 non-null  float64
 5   ListAgentFirstName           536077 non-null  str
 6   ListAgentLastName            540279 non-null  str
 7   Latitude                     460161 non-null  float64
 8   Longitude                    460161 non-null  float64
 9   UnparsedAddress              539634 non-null  str
 10  PropertyType                 540318 non-null  str
 11  LivingArea                   539766 non-null  float64
 12  ListPrice                    540318 non-null  float64
 13  DaysOnMarket                 540318 non-null  int64
 14  ListOfficeName               540318 non-null  str
 15  BuyerOfficeName              154582 non-null  str
 16  CoListOfficeName             121010 non-null  str
 17  ListAgentFullName            540228 non-null  str
 18  CoListAgentFirstName         120525 non-null  str
 19  CoListAgentLastName          120925 non-null  str
 20  BuyerAgentMlsId              156687 non-null  str
 21  BuyerAgentFirstName          156072 non-null  str
 22  BuyerAgentLastName           156795 non-null  str
 23  AssociationFeeFrequency      230872 non-null  str
 24  ListingKeyNumeric            540318 non-null  int64
 25  MLSAreaMajor                 467199 non-null  str
 26  CountyOrParish               540318 non-null  str
 27  MlsStatus                    540318 non-null  str
 28  ElementarySchool             64349 non-null   str
 29  AttachedGarageYN             445868 non-null  object
 30  ParkingTotal                 540298 non-null  float64
 31  PropertySubType              539067 non-null  str
 32  LotSizeAcres                 495771 non-null  float64
 33  SubdivisionName              198972 non-null  str
 34  BuyerOfficeAOR               144572 non-null  str
 35  YearBuilt                    539385 non-null  float64
 36  BuyerAgencyCompensationType  79005 non-null   str
 37  StreetNumberNumeric          539455 non-null  float64
 38  ListingId                    540318 non-null  str
 39  BathroomsTotalInteger        540263 non-null  float64
 40  City                         539744 non-null  str
 41  BuyerAgencyCompensation      78985 non-null   float64
 42  BedroomsTotal                540171 non-null  float64
 43  ContractStatusChangeDate     534265 non-null  datetime64[us]
 44  PurchaseContractDate         264303 non-null  datetime64[us]
 45  ListingContractDate          540318 non-null  datetime64[us]
 46  StateOrProvince              540265 non-null  str
 47  MiddleOrJuniorSchool         64476 non-null   str
 48  FireplaceYN                  539746 non-null  object
 49  Stories                      445808 non-null  float64
 50  HighSchool                   84446 non-null   str
 51  Levels                       481986 non-null  str
 52  LotSizeArea                  496610 non-null  float64
 53  MainLevelBedrooms            293741 non-null  float64
 54  NewConstructionYN            503240 non-null  object
 55  GarageSpaces                 510278 non-null  float64
 56  HighSchoolDistrict           377717 non-null  str
 57  PostalCode                   540305 non-null  str
 58  AssociationFee               410343 non-null  float64
 59  LotSizeSquareFeet            496435 non-null  float64
 60  year_month                   540318 non-null  str
 61  rate_30yr_fixed              540318 non-null  float64
 62  list_after_close_flag        396721 non-null  object
 63  purchase_after_close_flag    396721 non-null  object
dtypes: datetime64[us](4), float64(20), int64(3), object(5), str(32)
memory usage: 263.8+ MB

In [11]:
all(listed["ListingKey"] == listed["ListingKeyNumeric"])

True

In [42]:
sorted(sold.columns)

['AssociationFee',
 'AssociationFeeFrequency',
 'AttachedGarageYN',
 'BathroomsTotalInteger',
 'BedroomsTotal',
 'BuyerAgencyCompensation',
 'BuyerAgencyCompensationType',
 'BuyerAgentAOR',
 'BuyerAgentFirstName',
 'BuyerAgentLastName',
 'BuyerAgentMlsId',
 'BuyerOfficeAOR',
 'BuyerOfficeName',
 'City',
 'CloseDate',
 'ClosePrice',
 'CoListAgentFirstName',
 'CoListAgentLastName',
 'CoListOfficeName',
 'ContractStatusChangeDate',
 'CountyOrParish',
 'DaysOnMarket',
 'ElementarySchool',
 'FireplaceYN',
 'Flooring',
 'GarageSpaces',
 'HighSchool',
 'HighSchoolDistrict',
 'Latitude',
 'Levels',
 'ListAgentAOR',
 'ListAgentEmail',
 'ListAgentFirstName',
 'ListAgentFullName',
 'ListAgentLastName',
 'ListOfficeName',
 'ListPrice',
 'ListingContractDate',
 'ListingId',
 'ListingKey',
 'ListingKeyNumeric',
 'LivingArea',
 'Longitude',
 'LotSizeAcres',
 'LotSizeArea',
 'LotSizeSquareFeet',
 'MLSAreaMajor',
 'MainLevelBedrooms',
 'MiddleOrJuniorSchool',
 'MlsStatus',
 'NewConstructionYN',
 'OriginalListPrice',
 'ParkingTotal',
 'PoolPrivateYN',
 'PostalCode',
 'PropertySubType',
 'PropertyType',
 'PurchaseContractDate',
 'StateOrProvince',
 'Stories',
 'StreetNumberNumeric',
 'SubdivisionName',
 'UnparsedAddress',
 'ViewYN',
 'YearBuilt',
 'latfilled',
 'lonfilled',
 'rate_30yr_fixed',
 'year_month']

In [27]:
neg_days_addr = sold[sold["DaysOnMarket"] < 0]["UnparsedAddress"]

sold[sold["UnparsedAddress"].isin(neg_days_addr)].shape

(52, 69)

In [28]:
neg_days_addr.shape

(46,)

In [31]:
sold[(sold["UnparsedAddress"].isin(neg_days_addr)) & (sold["DaysOnMarket"] >= 0)]["UnparsedAddress"]

41879               45355 Miami Circle
86100     1025 N Tippecanoe Avenue 122
115149                 728 Malat Drive
155321          2230 N Eastwood Avenue
160684     28661 Crystal Heights Court
268544            8214 Platinum Street
Name: UnparsedAddress, dtype: str

In [36]:
sold[sold["UnparsedAddress"] == "1025 N Tippecanoe Avenue 122"][main_fields + ["DaysOnMarket"]]

,ListingKey,ListingContractDate,ListPrice,ClosePrice,PurchaseContractDate,CloseDate,LivingArea,BedroomsTotal,BathroomsTotalInteger,Latitude,Longitude,UnparsedAddress,DaysOnMarket
37001,1052236827,2023-12-08,135000.0,135000.0,2024-02-12,2024-03-08,708.0,1.0,1.0,34.118923,-117.260126,1025 N Tippecanoe Avenue 122,-19
86100,1069712675,2024-04-19,209900.0,210000.0,2024-05-03,2024-06-07,708.0,1.0,1.0,34.119162,-117.259896,1025 N Tippecanoe Avenue 122,9

In [41]:
listed[listed["BathroomsTotalInteger"] < 0][main_fields]

Empty DataFrame
Columns: [ListingKey, ListingContractDate, ListPrice, ClosePrice, PurchaseContractDate, CloseDate, LivingArea, BedroomsTotal, BathroomsTotalInteger, Latitude, Longitude, UnparsedAddress]
Index: []