In [1]:
import pandas as pd
import glob as gl
import matplotlib.pyplot as plt

In [2]:
listed2401 = pd.read_csv("CRMLSListing202401.csv")

listed2401.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road

In [3]:
listed_files = sorted(gl.glob("CRMLSListing*.csv"))
df = pd.concat([pd.read_csv(f, low_memory=False) for f in listed_files], ignore_index=True)

df.shape

(853413, 84)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 853413 entries, 0 to 853412
Data columns (total 84 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             850101 non-null  float64
 1   ListingKey                    853413 non-null  int64
 2   ListAgentEmail                780379 non-null  str
 3   CloseDate                     258103 non-null  str
 4   ClosePrice                    235487 non-null  float64
 5   ListAgentFirstName            848406 non-null  str
 6   ListAgentLastName             853337 non-null  str
 7   Latitude                      741479 non-null  float64
 8   Longitude                     742183 non-null  float64
 9   UnparsedAddress               851262 non-null  str
 10  PropertyType                  853413 non-null  str
 11  LivingArea                    746971 non-null  float64
 12  ListPrice                     851278 non-null  float64
 13  DaysOnMarket                  853413 non-null  int64
 14  ListOfficeName                853413 non-null  str
 15  BuyerOfficeName               247757 non-null  str
 16  CoListOfficeName              170928 non-null  str
 17  ListAgentFullName             853185 non-null  str
 18  CoListAgentFirstName          170299 non-null  str
 19  CoListAgentLastName           170786 non-null  str
 20  BuyerAgentMlsId               249361 non-null  str
 21  BuyerAgentFirstName           249195 non-null  str
 22  BuyerAgentLastName            250117 non-null  str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       246278 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             853413 non-null  int64
 27  MLSAreaMajor                  757063 non-null  str
 28  TaxAnnualAmount               6086 non-null    float64
 29  CountyOrParish                853412 non-null  str
 30  PropertyType.1                853413 non-null  str
 31  MlsStatus                     853413 non-null  str
 32  ElementarySchool              79286 non-null   str
 33  ListAgentFirstName.1          848406 non-null  str
 34  AttachedGarageYN              562479 non-null  object
 35  ParkingTotal                  801062 non-null  float64
 36  BuilderName                   29294 non-null   str
 37  PropertySubType               749275 non-null  str
 38  LotSizeAcres                  771905 non-null  float64
 39  SubdivisionName               285029 non-null  str
 40  BuyerOfficeAOR                235759 non-null  str
 41  YearBuilt                     783960 non-null  float64
 42  DaysOnMarket.1                853413 non-null  int64
 43  BuyerAgencyCompensationType   123538 non-null  str
 44  StreetNumberNumeric           849648 non-null  float64
 45  LivingArea.1                  746971 non-null  float64
 46  ListingId                     853413 non-null  str
 47  BathroomsTotalInteger         783481 non-null  float64
 48  City                          852453 non-null  str
 49  BuyerAgencyCompensation       123519 non-null  float64
 50  TaxYear                       868 non-null     float64
 51  BuildingAreaTotal             136801 non-null  float64
 52  BedroomsTotal                 750359 non-null  float64
 53  ContractStatusChangeDate      846541 non-null  str
 54  Longitude.1                   742183 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         19916 non-null   str
 57  PurchaseContractDate          369777 non-null  str
 58  ListingContractDate           853413 non-null  str
 59  BelowGradeFinishedArea        3422 non-null    float64
 60  BusinessType                  5979 non-null    str
 61  Latitude.1                    741479 non-null  float64
 62  ListPrice.1                   851278 non-null  float64
 63  StateOrProvince               853347 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          79378 non-null   str
 66  FireplaceYN                   730903 non-null  object
 67  Stories                       632176 non-null  float64
 68  HighSchool                    104334 non-null  str
 69  Levels                        689561 non-null  str
 70  ListAgentLastName.1           853337 non-null  str
 71  CloseDate.1                   258103 non-null  str
 72  LotSizeDimensions             48685 non-null   str
 73  LotSizeArea                   775684 non-null  float64
 74  MainLevelBedrooms             394847 non-null  float64
 75  NewConstructionYN             738704 non-null  object
 76  GarageSpaces                  691399 non-null  float64
 77  HighSchoolDistrict            514192 non-null  str
 78  PostalCode                    853205 non-null  str
 79  BuyerOfficeName.1             247757 non-null  str
 80  AssociationFee                577730 non-null  float64
 81  LotSizeSquareFeet             774608 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             851262 non-null  str
dtypes: float64(32), int64(4), object(3), str(45)
memory usage: 546.9+ MB

In [7]:
df[df.CloseDate.str.startswith("202")]

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
11,1249888.0,1073295259,sandra.mcfetridge@gmail.com,2024-05-01,1262555.0,Sandra,McFetridge,33.477414,-117.664879,33450 Paseo El Lazo,...,0.0,False,2.0,Capistrano Unified,92675,Compass,395.0,NaN,NaN,33450 Paseo El Lazo
19,650000.0,1073219502,lorijo@tcsn.net,2024-03-15,650000.0,Lori Jo,Stribling,35.508840,-120.690614,5405 San Benito Road,...,3.0,False,2.0,Atascadero Unified,93422,RE/MAX Parkside Real Estate,0.0,15521.0,NaN,5405 San Benito Road
23,105000.0,1073171653,chrisjcucchiara@gmail.com,2024-03-05,105000.0,Chris,Cucchiara,35.542360,-121.092195,0 Windsor Boulevard,...,NaN,False,NaN,NaN,93428,Keller Williams Realty Central Coast,0.0,4025.0,NaN,0 Windsor Boulevard
24,1025000.0,1073169832,doug@socalmodern.com,2024-05-02,962500.0,Douglas,Kramer,33.812886,-118.097004,3108 Kallin Avenue,...,3.0,False,1.0,Long Beach Unified,90808,Re/Max R. E. Specialists,0.0,5256.0,NaN,3108 Kallin Avenue
26,725000.0,1073164974,zachmickelson1@gmail.com,2024-04-30,725000.0,Zachary,Mickelson,33.740706,-117.888816,505 S Spruce Street,...,2.0,False,1.0,Santa Ana Unified,92703,Luxury Homes of California,0.0,6400.0,NaN,505 S Spruce Street
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853382,3588000.0,1152630260,NaN,2026-04-13,NaN,Cindy,Gee,37.655517,-121.906920,2577 Arlotta Pl,...,NaN,False,4.0,Pleasanton,94588,Keller Williams Tri-Valley,350.0,15524.0,NaN,2577 Arlotta Pl
853384,995000.0,1152588789,NaN,2026-04-07,NaN,Patricia,Elste,37.956681,-121.965838,5179 Paul Scarlet DR,...,NaN,False,4.0,Mount Diablo,94521,RE/MAX Accord,NaN,8500.0,NaN,5179 Paul Scarlet DR
853386,2295000.0,1152522022,NaN,2026-03-16,2380000.0,Lisa,Doyle,37.843639,-121.971421,286 Via Cima Ct,...,NaN,False,2.0,NaN,94526,Coldwell Banker Realty,NaN,14400.0,NaN,286 Via Cima Ct
853390,1050000.0,1152274870,NaN,2026-03-24,1050000.0,Heather,Gowdy,37.911605,-122.094572,1875 Lamplight Ct,...,NaN,False,2.0,Acalanes,94597,Compass,973.0,2940.0,NaN,1875 Lamplight Ct
853398,798000.0,1151667701,NaN,2026-04-21,NaN,Ting Yu,Zhu,37.996522,-121.685482,809 Bluestone Dr,...,NaN,False,3.0,NaN,94561-3066,Premier Homes & Loans Inc.,NaN,6300.0,NaN,809 Bluestone Dr

In [ ]:
df_test = pd.DataFrame()

for file in listed_files:
    list_df = pd.read_csv(file, low_memory=False)
    print(f"Loaded {list_df.shape[0]} rows from {file}")
    df_test = pd.concat([df_test, list_df], ignore_index=True)

In [10]:
df_test.shape

(853413, 84)

In [18]:
df["PropertyType"].unique()

<StringArray>
[ 'ManufacturedInPark',      'CommercialSale',         'Residential',
    'ResidentialLease',                'Land',   'ResidentialIncome',
     'CommercialLease', 'BusinessOpportunity']
Length: 8, dtype: str

In [29]:
df = df[df["PropertyType"] == "Residential"]

df.shape

(540391, 84)

In [25]:
df_null_cnt = (round(df.isnull().sum() / df.shape[0] * 100, 2)).reset_index()
df_null_cnt.columns = ["ColName", "NullPct"]
df_null_cnt.head()

             ColName  NullPct
0  OriginalListPrice     0.39
1         ListingKey     0.00
2     ListAgentEmail     8.56
3          CloseDate    69.76
4         ClosePrice    72.41

In [26]:
df_null_cnt["isSparse"] = df_null_cnt["NullPct"] >= 90.0
df_null_cnt

                         ColName  NullPct  isSparse
0              OriginalListPrice     0.39     False
1                     ListingKey     0.00     False
2                 ListAgentEmail     8.56     False
3                      CloseDate    69.76     False
4                     ClosePrice    72.41     False
..                           ...      ...       ...
79             BuyerOfficeName.1    70.97     False
80                AssociationFee    32.30     False
81             LotSizeSquareFeet     9.23     False
82  MiddleOrJuniorSchoolDistrict   100.00      True
83             UnparsedAddress.1     0.25     False

[84 rows x 3 columns]

In [19]:
num_cols = ["ListPrice", "ClosePrice", "LivingArea", "BedroomsTotal", "BathroomsTotalInteger", "Latitude", "Longitude"]
df[num_cols]

,ListPrice,ClosePrice,LivingArea,BedroomsTotal,BathroomsTotalInteger,Latitude,Longitude
0,90000.0,NaN,960.0,4.0,1.0,34.097939,-117.909653
1,1500000.0,NaN,NaN,NaN,0.0,33.121241,-117.081614
2,1340000.0,NaN,1301.0,2.0,2.0,34.052207,-118.408445
3,2500000.0,NaN,2788.0,4.0,3.0,33.496363,-117.691677
4,3150000.0,NaN,3250.0,6.0,4.0,34.119345,-118.111254
...,...,...,...,...,...,...,...
853408,6395000.0,NaN,NaN,NaN,0.0,37.883215,-122.261440
853409,839900.0,NaN,1598.0,4.0,2.0,32.621759,-116.996024
853410,2849000.0,NaN,3199.0,5.0,5.0,33.102975,-117.299101
853411,1149000.0,NaN,1398.0,4.0,2.0,32.579821,-117.104163
853412,1149000.0,NaN,NaN,NaN,0.0,32.580200,-117.116500

In [17]:
date_cols = [col for col in df.columns if "date" in col.lower()]
date_cols

['CloseDate',
 'ContractStatusChangeDate',
 'PurchaseContractDate',
 'ListingContractDate',
 'CloseDate.1']

In [18]:
df[date_cols].info()

<class 'pandas.DataFrame'>
RangeIndex: 853413 entries, 0 to 853412
Data columns (total 5 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CloseDate                 258103 non-null  str
 1   ContractStatusChangeDate  846541 non-null  str
 2   PurchaseContractDate      369777 non-null  str
 3   ListingContractDate       853413 non-null  str
 4   CloseDate.1               258103 non-null  str
dtypes: str(5)
memory usage: 32.6 MB

In [ ]:
df_null_cnt[